### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ndzamboni** [ndzamboni/manchester-orchestra#1]
- [x] Make page responsive (currently not)
- [x] Find some JavaScript to give scrolling a fun attribute
- [x] Styling can use some updates. Make the style consistent with the theme (modern)

**Comment by ndzamboni** [comment]
done!
